### ISSUE TITLE
pull-through of new versions

### ISSUE THREAD

**Issue by dirkboye** [g3ngar/verdaccio-offline-storage#1]
i really like the feature to have all packages visible in the webui (even those not uploaded) but i'd like
to be able to still "pull-through" new version from the uplink if version is not available.

is your solution to have 2 webuis running with the same local-storage?
(and 1 webui has this plugin installed)
would that work?

**Comment by g3ngar** [comment]
It's the same ui. The plugin only overrides the `get all existing packages` behavior of `local-storage`. Probably moving that feature to a new package/plugin from which this one would be based would be a nice thing to do. Or try to code a "smart" detection of offline environments. Dunno, gotta think a little about that.

**Comment by g3ngar** [comment]
PR are welcome btw

**Comment by ronyf** [comment]
@g3ngar @dirkboye I think I fixed it in #3

**Comment by carlos-penton** [comment]
See v2.0.0 please
